import './AdvancedSettings.svelte.css.proxy.js';
/* src/components/AdvancedSettings.svelte generated by Svelte v3.41.0 */
import {
	SvelteComponent,
	add_render_callback,
	append,
	attr,
	binding_callbacks,
	component_subscribe,
	create_bidirectional_transition,
	destroy_each,
	detach,
	element,
	init,
	insert,
	listen,
	null_to_empty,
	run_all,
	safe_not_equal,
	space,
	text,
	toggle_class
} from "../_snowpack/pkg/svelte/internal.js";

import { fly } from "../_snowpack/pkg/svelte/transition.js";

import {
	rollHasExpressions,
	playExpressionsOnOff,
	rollPedalingOnOff,
	useMidiTempoEventsOnOff,
	userSettings
} from "../stores.js";

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[15] = list[i];
	return child_ctx;
}

// (125:4) {#each themes as theme}
function create_each_block(ctx) {
	let button;
	let button_class_value;
	let mounted;
	let dispose;

	function click_handler() {
		return /*click_handler*/ ctx[13](/*theme*/ ctx[15]);
	}

	return {
		c() {
			button = element("button");
			attr(button, "class", button_class_value = "" + (null_to_empty(/*theme*/ ctx[15]) + " svelte-3yrbwy"));
			toggle_class(button, "active", /*$userSettings*/ ctx[0].theme === /*theme*/ ctx[15]);
		},
		m(target, anchor) {
			insert(target, button, anchor);

			if (!mounted) {
				dispose = listen(button, "click", click_handler);
				mounted = true;
			}
		},
		p(new_ctx, dirty) {
			ctx = new_ctx;

			if (dirty & /*$userSettings, themes*/ 65) {
				toggle_class(button, "active", /*$userSettings*/ ctx[0].theme === /*theme*/ ctx[15]);
			}
		},
		d(detaching) {
			if (detaching) detach(button);
			mounted = false;
			dispose();
		}
	};
}

function create_fragment(ctx) {
	let div7;
	let fieldset0;
	let legend0;
	let t1;
	let div0;
	let t2;
	let input0;
	let t3;
	let div1;
	let t4;
	let input1;
	let t5;
	let div2;
	let t6;
	let input2;
	let t7;
	let fieldset1;
	let legend1;
	let t9;
	let div3;
	let t10;
	let input3;
	let input3_disabled_value;
	let t11;
	let div4;
	let t12;
	let input4;
	let input4_disabled_value;
	let t13;
	let div5;
	let t14;
	let input5;
	let t15;
	let div6;
	let t16;
	let div7_transition;
	let current;
	let mounted;
	let dispose;
	let each_value = /*themes*/ ctx[6];
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	return {
		c() {
			div7 = element("div");
			fieldset0 = element("fieldset");
			legend0 = element("legend");
			legend0.textContent = "Visualization Settings";
			t1 = space();
			div0 = element("div");
			t2 = text("Show Details for Active Notes:\n      ");
			input0 = element("input");
			t3 = space();
			div1 = element("div");
			t4 = text("Display Note Velocities:\n      ");
			input1 = element("input");
			t5 = space();
			div2 = element("div");
			t6 = text("Highlight Enabled Holes:\n      ");
			input2 = element("input");
			t7 = space();
			fieldset1 = element("fieldset");
			legend1 = element("legend");
			legend1.textContent = "Roll Emulation Settings";
			t9 = space();
			div3 = element("div");
			t10 = text("Play Expressions:\n      ");
			input3 = element("input");
			t11 = space();
			div4 = element("div");
			t12 = text("Use Roll Pedaling:\n      ");
			input4 = element("input");
			t13 = space();
			div5 = element("div");
			t14 = text("Emulate Roll Acceleration:\n      ");
			input5 = element("input");
			t15 = space();
			div6 = element("div");
			t16 = text("Theme:\n    ");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			attr(legend0, "class", "svelte-3yrbwy");
			attr(input0, "type", "checkbox");
			attr(div0, "class", "svelte-3yrbwy");
			attr(input1, "type", "checkbox");
			attr(div1, "class", "svelte-3yrbwy");
			attr(input2, "type", "checkbox");
			attr(div2, "class", "svelte-3yrbwy");
			attr(fieldset0, "class", "svelte-3yrbwy");
			attr(legend1, "class", "svelte-3yrbwy");
			attr(input3, "type", "checkbox");
			input3.disabled = input3_disabled_value = !/*$rollHasExpressions*/ ctx[2];
			attr(div3, "class", "svelte-3yrbwy");
			attr(input4, "type", "checkbox");
			input4.disabled = input4_disabled_value = !/*$rollHasExpressions*/ ctx[2];
			attr(div4, "class", "svelte-3yrbwy");
			attr(input5, "type", "checkbox");
			attr(div5, "class", "svelte-3yrbwy");
			attr(fieldset1, "class", "svelte-3yrbwy");
			attr(div7, "id", "settings-panel");
			attr(div7, "class", "svelte-3yrbwy");
		},
		m(target, anchor) {
			insert(target, div7, anchor);
			append(div7, fieldset0);
			append(fieldset0, legend0);
			append(fieldset0, t1);
			append(fieldset0, div0);
			append(div0, t2);
			append(div0, input0);
			input0.checked = /*$userSettings*/ ctx[0].activeNoteDetails;
			append(fieldset0, t3);
			append(fieldset0, div1);
			append(div1, t4);
			append(div1, input1);
			input1.checked = /*$userSettings*/ ctx[0].showNoteVelocities;
			append(fieldset0, t5);
			append(fieldset0, div2);
			append(div2, t6);
			append(div2, input2);
			input2.checked = /*$userSettings*/ ctx[0].highlightEnabledHoles;
			append(div7, t7);
			append(div7, fieldset1);
			append(fieldset1, legend1);
			append(fieldset1, t9);
			append(fieldset1, div3);
			append(div3, t10);
			append(div3, input3);
			input3.checked = /*$playExpressionsOnOff*/ ctx[3];
			append(fieldset1, t11);
			append(fieldset1, div4);
			append(div4, t12);
			append(div4, input4);
			input4.checked = /*$rollPedalingOnOff*/ ctx[4];
			append(fieldset1, t13);
			append(fieldset1, div5);
			append(div5, t14);
			append(div5, input5);
			input5.checked = /*$useMidiTempoEventsOnOff*/ ctx[5];
			append(div7, t15);
			append(div7, div6);
			append(div6, t16);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(div6, null);
			}

			/*div7_binding*/ ctx[14](div7);
			current = true;

			if (!mounted) {
				dispose = [
					listen(input0, "change", /*input0_change_handler*/ ctx[7]),
					listen(input1, "change", /*input1_change_handler*/ ctx[8]),
					listen(input2, "change", /*input2_change_handler*/ ctx[9]),
					listen(input3, "change", /*input3_change_handler*/ ctx[10]),
					listen(input4, "change", /*input4_change_handler*/ ctx[11]),
					listen(input5, "change", /*input5_change_handler*/ ctx[12])
				];

				mounted = true;
			}
		},
		p(new_ctx, [dirty]) {
			ctx = new_ctx;

			if (dirty & /*$userSettings*/ 1) {
				input0.checked = /*$userSettings*/ ctx[0].activeNoteDetails;
			}

			if (dirty & /*$userSettings*/ 1) {
				input1.checked = /*$userSettings*/ ctx[0].showNoteVelocities;
			}

			if (dirty & /*$userSettings*/ 1) {
				input2.checked = /*$userSettings*/ ctx[0].highlightEnabledHoles;
			}

			if (!current || dirty & /*$rollHasExpressions*/ 4 && input3_disabled_value !== (input3_disabled_value = !/*$rollHasExpressions*/ ctx[2])) {
				input3.disabled = input3_disabled_value;
			}

			if (dirty & /*$playExpressionsOnOff*/ 8) {
				input3.checked = /*$playExpressionsOnOff*/ ctx[3];
			}

			if (!current || dirty & /*$rollHasExpressions*/ 4 && input4_disabled_value !== (input4_disabled_value = !/*$rollHasExpressions*/ ctx[2])) {
				input4.disabled = input4_disabled_value;
			}

			if (dirty & /*$rollPedalingOnOff*/ 16) {
				input4.checked = /*$rollPedalingOnOff*/ ctx[4];
			}

			if (dirty & /*$useMidiTempoEventsOnOff*/ 32) {
				input5.checked = /*$useMidiTempoEventsOnOff*/ ctx[5];
			}

			if (dirty & /*themes, $userSettings, userSettings*/ 65) {
				each_value = /*themes*/ ctx[6];
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(div6, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}

				each_blocks.length = each_value.length;
			}
		},
		i(local) {
			if (current) return;

			if (local) {
				add_render_callback(() => {
					if (!div7_transition) div7_transition = create_bidirectional_transition(
						div7,
						fly,
						{
							delay: 0,
							duration: 300,
							x: parseInt(window.getComputedStyle(/*el*/ ctx[1]).width, 10),
							y: 0,
							opacity: 1
						},
						true
					);

					div7_transition.run(1);
				});
			}

			current = true;
		},
		o(local) {
			if (local) {
				if (!div7_transition) div7_transition = create_bidirectional_transition(
					div7,
					fly,
					{
						delay: 0,
						duration: 300,
						x: parseInt(window.getComputedStyle(/*el*/ ctx[1]).width, 10),
						y: 0,
						opacity: 1
					},
					false
				);

				div7_transition.run(0);
			}

			current = false;
		},
		d(detaching) {
			if (detaching) detach(div7);
			destroy_each(each_blocks, detaching);
			/*div7_binding*/ ctx[14](null);
			if (detaching && div7_transition) div7_transition.end();
			mounted = false;
			run_all(dispose);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let $userSettings;
	let $rollHasExpressions;
	let $playExpressionsOnOff;
	let $rollPedalingOnOff;
	let $useMidiTempoEventsOnOff;
	component_subscribe($$self, userSettings, $$value => $$invalidate(0, $userSettings = $$value));
	component_subscribe($$self, rollHasExpressions, $$value => $$invalidate(2, $rollHasExpressions = $$value));
	component_subscribe($$self, playExpressionsOnOff, $$value => $$invalidate(3, $playExpressionsOnOff = $$value));
	component_subscribe($$self, rollPedalingOnOff, $$value => $$invalidate(4, $rollPedalingOnOff = $$value));
	component_subscribe($$self, useMidiTempoEventsOnOff, $$value => $$invalidate(5, $useMidiTempoEventsOnOff = $$value));
	let el;
	const themes = ["cardinal", "blue", "green", "grey"];

	function input0_change_handler() {
		$userSettings.activeNoteDetails = this.checked;
		userSettings.set($userSettings);
	}

	function input1_change_handler() {
		$userSettings.showNoteVelocities = this.checked;
		userSettings.set($userSettings);
	}

	function input2_change_handler() {
		$userSettings.highlightEnabledHoles = this.checked;
		userSettings.set($userSettings);
	}

	function input3_change_handler() {
		$playExpressionsOnOff = this.checked;
		playExpressionsOnOff.set($playExpressionsOnOff);
	}

	function input4_change_handler() {
		$rollPedalingOnOff = this.checked;
		rollPedalingOnOff.set($rollPedalingOnOff);
	}

	function input5_change_handler() {
		$useMidiTempoEventsOnOff = this.checked;
		useMidiTempoEventsOnOff.set($useMidiTempoEventsOnOff);
	}

	const click_handler = theme => userSettings.update(settings => ({ ...settings, theme }));

	function div7_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			el = $$value;
			$$invalidate(1, el);
		});
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*$userSettings*/ 1) {
			$: document.body.className = $userSettings.theme;
		}
	};

	return [
		$userSettings,
		el,
		$rollHasExpressions,
		$playExpressionsOnOff,
		$rollPedalingOnOff,
		$useMidiTempoEventsOnOff,
		themes,
		input0_change_handler,
		input1_change_handler,
		input2_change_handler,
		input3_change_handler,
		input4_change_handler,
		input5_change_handler,
		click_handler,
		div7_binding
	];
}

class AdvancedSettings extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default AdvancedSettings;