// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = "#keyboard.svelte-1l8xgwp.svelte-1l8xgwp.svelte-1l8xgwp{margin:1em auto;position:relative;width:fit-content}div#keys.svelte-1l8xgwp.svelte-1l8xgwp.svelte-1l8xgwp{border-top:2px solid #222;display:block;height:calc(1.8vw * 6);margin:0;padding:0;width:100%}div#keys.svelte-1l8xgwp div.svelte-1l8xgwp.svelte-1l8xgwp{float:left;position:relative;width:1.8vw}div#keys.svelte-1l8xgwp div.svelte-1l8xgwp .svelte-1l8xgwp:first-child{background:linear-gradient(-30deg, #f5f5f5, #fff);border-radius:0 0 3px 3px;border:1px solid #ccc;box-shadow:inset 0 1px 0px #fff, inset 0 -1px 0px #fff, inset 1px 0px 0px #fff, inset -1px 0px 0px #fff, 0 4px 3px rgba(0, 0, 0, 0.7);display:block;height:calc(1.8vw * 6 - 20px)}div#keys.svelte-1l8xgwp div.svelte-1l8xgwp .svelte-1l8xgwp:first-child:active,div#keys.svelte-1l8xgwp div.svelte-1l8xgwp :first-child.depressed{box-shadow:0 2px 2px rgba(0, 0, 0, 0.4);height:calc(1.8vw * 6 - 24px);position:relative;top:2px}div#keys.svelte-1l8xgwp div.svelte-1l8xgwp .svelte-1l8xgwp:first-child:active:before,div#keys.svelte-1l8xgwp div.svelte-1l8xgwp :first-child.depressed:before{border-color:transparent transparent transparent rgba(0, 0, 0, 0.1);border-style:solid;border-width:calc(1.8vw * 6 - 24px) 5px 0px;content:\"\";height:0px;left:0px;position:absolute;top:0px;width:0px}div#keys.svelte-1l8xgwp div.svelte-1l8xgwp .svelte-1l8xgwp:first-child:active:after,div#keys.svelte-1l8xgwp div.svelte-1l8xgwp :first-child.depressed:after{border-color:transparent rgba(0, 0, 0, 0.1) transparent transparent;border-style:solid;border-width:calc(1.8vw * 6 - 24px) 5px 0px;content:\"\";height:0px;position:absolute;right:0px;top:0px;width:0px}div#keys.svelte-1l8xgwp div.svelte-1l8xgwp :first-child.depressed{background:#b5e2ff}div#keys.svelte-1l8xgwp div.svelte-1l8xgwp .svelte-1l8xgwp:nth-child(2){background:linear-gradient(-20deg, #333, #000, #333);border-color:#666 #222 #111 #555;border-radius:0 0 2px 2px;border-style:solid;border-width:1px 2px 7px;box-shadow:inset 0px -1px 2px rgba(255, 255, 255, 0.4), 0 2px 3px rgba(0, 0, 0, 0.4);height:calc(1.8vw * 3);left:calc(1.8vw - 2px - 0.45vw);position:absolute;top:0px;width:0.9vw;z-index:10}div#keys.svelte-1l8xgwp div.svelte-1l8xgwp .svelte-1l8xgwp:nth-child(2):active,div#keys.svelte-1l8xgwp div.svelte-1l8xgwp :nth-child(2).depressed{border-bottom-width:2px;box-shadow:inset 0px -1px 1px rgba(255, 255, 255, 0.4), 0 1px 0px rgba(0, 0, 0, 0.8), 0 2px 2px rgba(0, 0, 0, 0.4), 0 -1px 0px #000;height:calc(1.8vw * 3 + 3px)}div#keys.svelte-1l8xgwp div.svelte-1l8xgwp :nth-child(2).depressed{background:#b5e2ff}";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}