/* src/components/KeyboardShortcuts.svelte generated by Svelte v3.29.4 */
import {
	SvelteComponent,
	component_subscribe,
	init,
	listen,
	noop,
	run_all,
	safe_not_equal,
	set_store_value
} from "../_snowpack/pkg/svelte/internal.js";

import { get } from "../_snowpack/pkg/svelte/store.js";
import { pedalling, volume, tempoControl } from "../stores.js";

function create_fragment(ctx) {
	let mounted;
	let dispose;

	return {
		c: noop,
		m(target, anchor) {
			if (!mounted) {
				dispose = [
					listen(window, "keydown", /*keydown_handler*/ ctx[5]),
					listen(window, "keyup", /*keyup_handler*/ ctx[6])
				];

				mounted = true;
			}
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			mounted = false;
			run_all(dispose);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let $pedalling;
	component_subscribe($$self, pedalling, $$value => $$invalidate(0, $pedalling = $$value));

	const keyMap = Object.freeze({
		SOFT: "KeyQ",
		SUSTAIN: "KeyC",
		ACCENT: "Comma",
		VOLUME_UP: "BracketRight",
		VOLUME_DOWN: "BracketLeft",
		TEMPO_UP: "KeyE",
		TEMPO_DOWN: "KeyW"
	});

	const config = {
		volume: {
			store: volume,
			min: 0,
			max: 4,
			delta: 0.1,
			shiftDelta: 0.4,
			ctrlDelta: 0.05,
			precision: 2
		},
		tempo: {
			store: tempoControl,
			min: 0.1,
			max: 4,
			delta: 0.05,
			shiftDelta: 0.1,
			ctrlDelta: 0.01,
			precision: 2
		}
	};

	const enforcePrecision = (value, precision) => {
		const multiplier = 10 ** (precision || 0);
		return Math.round(value * multiplier) / multiplier;
	};

	const clamp = (value, min, max) => Math.min(Math.max(value, min), max);

	const updateStore = ({ store, min, max, delta, shiftDelta, ctrlDelta, precision }, { shiftKey, ctrlKey }, increment) => {
		const d = (increment ? 1 : -1) * (shiftKey && shiftDelta || ctrlKey && ctrlDelta || delta);
		store.set(enforcePrecision(clamp(get(store) + d, min, max), precision));
	};

	const increment = (...args) => updateStore(...args, true);
	const decrement = (...args) => updateStore(...args, false);

	const keydown_handler = event => {
		switch (event.code) {
			case keyMap.SOFT:
				if (!event.ctrlKey && !event.shiftKey) event.preventDefault();
				set_store_value(pedalling, $pedalling.soft = true, $pedalling);
				break;
			case keyMap.SUSTAIN:
				if (!event.ctrlKey && !event.shiftKey) event.preventDefault();
				set_store_value(pedalling, $pedalling.sustain = true, $pedalling);
				break;
			case keyMap.ACCENT:
				if (!event.ctrlKey && !event.shiftKey) event.preventDefault();
				set_store_value(pedalling, $pedalling.accent = true, $pedalling);
				break;
			case keyMap.VOLUME_UP:
				event.preventDefault();
				increment(config.volume, event);
				break;
			case keyMap.VOLUME_DOWN:
				event.preventDefault();
				decrement(config.volume, event);
				break;
			case keyMap.TEMPO_UP:
				event.preventDefault();
				increment(config.tempo, event);
				break;
			case keyMap.TEMPO_DOWN:
				event.preventDefault();
				decrement(config.tempo, event);
				break;
		} // no default
	};

	const keyup_handler = ({ code }) => {
		switch (code) {
			case keyMap.SOFT:
				set_store_value(pedalling, $pedalling.soft = false, $pedalling);
				break;
			case keyMap.SUSTAIN:
				set_store_value(pedalling, $pedalling.sustain = false, $pedalling);
				break;
			case keyMap.ACCENT:
				set_store_value(pedalling, $pedalling.accent = false, $pedalling);
				break;
		} // no default
	};

	return [
		$pedalling,
		keyMap,
		config,
		increment,
		decrement,
		keydown_handler,
		keyup_handler
	];
}

class KeyboardShortcuts extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default KeyboardShortcuts;