// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = "#roll-viewer-controls.svelte-h38w6c.svelte-h38w6c{background:rgba(0, 0, 0, 0.4);border-radius:4px;opacity:0;pointer-events:none;left:50%;padding:8px;position:absolute;top:8px;transform:translateX(-50%);transition:opacity 500ms ease;z-index:25}#roll-viewer-controls.svelte-h38w6c.svelte-h38w6c:hover{opacity:1;pointer-events:all}#roll-viewer-controls.svelte-h38w6c button.svelte-h38w6c{background:none;border:none;color:#ffffff;cursor:pointer;margin:0;padding:0.35em 0.8em;transition:all 0.2s}#roll-viewer-controls.svelte-h38w6c button.svelte-h38w6c:focus,#roll-viewer-controls.svelte-h38w6c button.svelte-h38w6c:active{outline:0}#roll-viewer-controls.svelte-h38w6c button.svelte-h38w6c:hover{outline:1px solid white}#roll-viewer-controls.svelte-h38w6c button.svelte-h38w6c:active{color:grey}#roll-viewer.svelte-h38w6c.svelte-h38w6c{position:relative;height:100%;width:100%}#roll-viewer.svelte-h38w6c.svelte-h38w6c::before{background:#8c1515;content:\"\";display:block;height:1px;pointer-events:none;position:absolute;top:50%;width:100%;z-index:3}#roll-viewer.svelte-h38w6c.svelte-h38w6c::after{background-color:#dad7cb;bottom:0;content:\" \";left:0;mix-blend-mode:multiply;pointer-events:none;position:absolute;right:0;top:0}#roll-viewer.svelte-h38w6c:hover+#roll-viewer-controls.svelte-h38w6c{opacity:1;pointer-events:all}#roll-viewer.svelte-h38w6c canvas{background:white !important}#roll-viewer.svelte-h38w6c .openseadragon-canvas:focus{outline:none}#roll-viewer.svelte-h38w6c mark{background-color:transparent;mix-blend-mode:multiply}#roll-viewer.svelte-h38w6c mark.active{animation:svelte-h38w6c-mark-recede 0.5s ease-in-out;background-color:yellow;box-shadow:0 0 5px yellow}#roll-viewer.svelte-h38w6c mark:hover{background-color:transparent;box-shadow:none;mix-blend-mode:normal;outline:6px solid darkturquoise;outline-offset:8px;z-index:4}#roll-viewer.svelte-h38w6c mark:hover[data-info]::after{background-color:darkturquoise;color:white;content:attr(data-info);display:block;font-weight:bold;left:calc( 100% + 8px + 6px );padding:8px 10px 8px 4px;position:absolute;text-shadow:0px 0px 8px black;top:-14px}#roll-viewer.svelte-h38w6c svg rect{fill:none;pointer-events:all}@keyframes svelte-h38w6c-mark-recede{from{border-radius:30%;mix-blend-mode:normal}}";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}