import './RollViewer.svelte.css.proxy.js';
/* src/components/RollViewer.svelte generated by Svelte v3.41.0 */
import {
	SvelteComponent,
	add_flush_callback,
	add_render_callback,
	append,
	attr,
	bind,
	binding_callbacks,
	check_outros,
	component_subscribe,
	create_bidirectional_transition,
	create_component,
	destroy_component,
	detach,
	element,
	group_outros,
	init,
	insert,
	listen,
	mount_component,
	prevent_default,
	run_all,
	safe_not_equal,
	set_style,
	space,
	toggle_class,
	transition_in,
	transition_out
} from "../_snowpack/pkg/svelte/internal.js";

import { onMount } from "../_snowpack/pkg/svelte.js";
import { fade } from "../_snowpack/pkg/svelte/transition.js";
import OpenSeadragon from "../_snowpack/pkg/openseadragon.js";

import {
	rollMetadata,
	currentTick,
	userSettings,
	animatePan,
	playExpressionsOnOff,
	rollPedalingOnOff,
	playbackProgress
} from "../stores.js";

import {
	clamp,
	mapToRange,
	normalizeInRange,
	getHoleLabel,
	getHoleType
} from "../utils.js";

import RollViewerControls from "./RollViewerControls.svelte.js";

function create_if_block_1(ctx) {
	let p;
	let p_transition;
	let current;

	return {
		c() {
			p = element("p");
			p.textContent = "Downloading roll image...";
			attr(p, "class", "svelte-11ybd8n");
		},
		m(target, anchor) {
			insert(target, p, anchor);
			current = true;
		},
		i(local) {
			if (current) return;

			add_render_callback(() => {
				if (!p_transition) p_transition = create_bidirectional_transition(p, fade, {}, true);
				p_transition.run(1);
			});

			current = true;
		},
		o(local) {
			if (!p_transition) p_transition = create_bidirectional_transition(p, fade, {}, false);
			p_transition.run(0);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(p);
			if (detaching && p_transition) p_transition.end();
		}
	};
}

// (463:2) {#if showControls}
function create_if_block(ctx) {
	let rollviewercontrols;
	let updating_strafing;
	let current;

	function rollviewercontrols_strafing_binding(value) {
		/*rollviewercontrols_strafing_binding*/ ctx[16](value);
	}

	let rollviewercontrols_props = {
		openSeadragon: /*openSeadragon*/ ctx[0],
		minZoomLevel,
		maxZoomLevel,
		panByIncrement: /*panByIncrement*/ ctx[9]
	};

	if (/*strafing*/ ctx[2] !== void 0) {
		rollviewercontrols_props.strafing = /*strafing*/ ctx[2];
	}

	rollviewercontrols = new RollViewerControls({ props: rollviewercontrols_props });
	binding_callbacks.push(() => bind(rollviewercontrols, 'strafing', rollviewercontrols_strafing_binding));

	return {
		c() {
			create_component(rollviewercontrols.$$.fragment);
		},
		m(target, anchor) {
			mount_component(rollviewercontrols, target, anchor);
			current = true;
		},
		p(ctx, dirty) {
			const rollviewercontrols_changes = {};
			if (dirty[0] & /*openSeadragon*/ 1) rollviewercontrols_changes.openSeadragon = /*openSeadragon*/ ctx[0];

			if (!updating_strafing && dirty[0] & /*strafing*/ 4) {
				updating_strafing = true;
				rollviewercontrols_changes.strafing = /*strafing*/ ctx[2];
				add_flush_callback(() => updating_strafing = false);
			}

			rollviewercontrols.$set(rollviewercontrols_changes);
		},
		i(local) {
			if (current) return;
			transition_in(rollviewercontrols.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(rollviewercontrols.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(rollviewercontrols, detaching);
		}
	};
}

function create_fragment(ctx) {
	let div;
	let t;
	let current;
	let mounted;
	let dispose;
	let if_block0 = !/*rollImageReady*/ ctx[3] && create_if_block_1(ctx);
	let if_block1 = /*showControls*/ ctx[4] && create_if_block(ctx);

	return {
		c() {
			div = element("div");
			if (if_block0) if_block0.c();
			t = space();
			if (if_block1) if_block1.c();
			attr(div, "id", "roll-viewer");
			set_style(div, "--trackerbar-height", /*trackerbarHeight*/ ctx[5] + "px");
			attr(div, "class", "svelte-11ybd8n");
			toggle_class(div, "active-note-details", /*$userSettings*/ ctx[6].activeNoteDetails);
			toggle_class(div, "highlight-enabled-holes", /*$userSettings*/ ctx[6].highlightEnabledHoles);
			toggle_class(div, "show-note-velocities", /*$userSettings*/ ctx[6].showNoteVelocities);
			toggle_class(div, "use-roll-pedaling", /*$rollPedalingOnOff*/ ctx[7]);
			toggle_class(div, "play-expressions", /*$playExpressionsOnOff*/ ctx[8]);
		},
		m(target, anchor) {
			insert(target, div, anchor);
			if (if_block0) if_block0.m(div, null);
			append(div, t);
			if (if_block1) if_block1.m(div, null);
			current = true;

			if (!mounted) {
				dispose = [
					listen(div, "mouseenter", /*mouseenter_handler*/ ctx[17]),
					listen(div, "mouseleave", /*mouseleave_handler*/ ctx[18]),
					listen(div, "wheel", prevent_default(/*wheel_handler*/ ctx[19]), true)
				];

				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (!/*rollImageReady*/ ctx[3]) {
				if (if_block0) {
					if (dirty[0] & /*rollImageReady*/ 8) {
						transition_in(if_block0, 1);
					}
				} else {
					if_block0 = create_if_block_1(ctx);
					if_block0.c();
					transition_in(if_block0, 1);
					if_block0.m(div, t);
				}
			} else if (if_block0) {
				group_outros();

				transition_out(if_block0, 1, 1, () => {
					if_block0 = null;
				});

				check_outros();
			}

			if (/*showControls*/ ctx[4]) {
				if (if_block1) {
					if_block1.p(ctx, dirty);

					if (dirty[0] & /*showControls*/ 16) {
						transition_in(if_block1, 1);
					}
				} else {
					if_block1 = create_if_block(ctx);
					if_block1.c();
					transition_in(if_block1, 1);
					if_block1.m(div, null);
				}
			} else if (if_block1) {
				group_outros();

				transition_out(if_block1, 1, 1, () => {
					if_block1 = null;
				});

				check_outros();
			}

			if (!current || dirty[0] & /*trackerbarHeight*/ 32) {
				set_style(div, "--trackerbar-height", /*trackerbarHeight*/ ctx[5] + "px");
			}

			if (dirty[0] & /*$userSettings*/ 64) {
				toggle_class(div, "active-note-details", /*$userSettings*/ ctx[6].activeNoteDetails);
			}

			if (dirty[0] & /*$userSettings*/ 64) {
				toggle_class(div, "highlight-enabled-holes", /*$userSettings*/ ctx[6].highlightEnabledHoles);
			}

			if (dirty[0] & /*$userSettings*/ 64) {
				toggle_class(div, "show-note-velocities", /*$userSettings*/ ctx[6].showNoteVelocities);
			}

			if (dirty[0] & /*$rollPedalingOnOff*/ 128) {
				toggle_class(div, "use-roll-pedaling", /*$rollPedalingOnOff*/ ctx[7]);
			}

			if (dirty[0] & /*$playExpressionsOnOff*/ 256) {
				toggle_class(div, "play-expressions", /*$playExpressionsOnOff*/ ctx[8]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(if_block0);
			transition_in(if_block1);
			current = true;
		},
		o(local) {
			transition_out(if_block0);
			transition_out(if_block1);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div);
			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			mounted = false;
			run_all(dispose);
		}
	};
}

const defaultHoleColor = "60, 100%, 50%"; // yellow (default)
const controlHoleColor = "120, 73%, 75%"; // light green
const pedalHoleColor = "39, 100%, 50%"; // orange;
const defaultZoomLevel = 1;
const minZoomLevel = 0.1;
const maxZoomLevel = 4;

function instance($$self, $$props, $$invalidate) {
	let scrollDownwards;
	let $rollMetadata;
	let $currentTick;
	let $playbackProgress;
	let $animatePan;
	let $userSettings;
	let $rollPedalingOnOff;
	let $playExpressionsOnOff;
	component_subscribe($$self, rollMetadata, $$value => $$invalidate(14, $rollMetadata = $$value));
	component_subscribe($$self, currentTick, $$value => $$invalidate(15, $currentTick = $$value));
	component_subscribe($$self, playbackProgress, $$value => $$invalidate(27, $playbackProgress = $$value));
	component_subscribe($$self, animatePan, $$value => $$invalidate(28, $animatePan = $$value));
	component_subscribe($$self, userSettings, $$value => $$invalidate(6, $userSettings = $$value));
	component_subscribe($$self, rollPedalingOnOff, $$value => $$invalidate(7, $rollPedalingOnOff = $$value));
	component_subscribe($$self, playExpressionsOnOff, $$value => $$invalidate(8, $playExpressionsOnOff = $$value));
	let { imageUrl } = $$props;
	let { holesByTickInterval } = $$props;
	let { skipToTick } = $$props;

	// This is the "coolwarm" color map -- blue to red
	// RdYlBu (reversed) sort of works, but the yellows are too ambiguous
	// (values in H, S, L)
	const holeColorMap = [
		"232, 53%, 49%",
		"229, 64%, 58%",
		"225, 78%, 66%",
		"223, 91%, 73%",
		"221, 98%, 79%",
		"219, 95%, 83%",
		"217, 73%, 86%",
		"21, 28%, 86%",
		"20, 69%, 83%",
		"18, 85%, 79%",
		"16, 85%, 73%",
		"13, 80%, 67%",
		"9, 70%, 59%",
		"2, 59%, 51%",
		"348, 96%, 36%"
	];

	let openSeadragon;
	let viewport;
	let firstHolePx;
	let strafing = false;
	let rollImageReady;
	let marks = [];
	let hoveredMark;
	let showControls;
	let imageLength;
	let imageWidth;
	let avgHoleWidth;
	let trackerbarHeight;

	const calculateHoleColors = holeData => {
		const velocities = holeData.map(({ v }) => v).filter(v => v);
		const minNoteVelocity = velocities.length ? Math.min(...velocities) : 64;
		const maxNoteVelocity = velocities.length ? Math.max(...velocities) : 64;
		const getNoteHoleColor = ({ v: velocity }) => holeColorMap[Math.round(mapToRange(normalizeInRange(velocity, minNoteVelocity, maxNoteVelocity), 0, holeColorMap.length - 1))];

		holeData.forEach(hole => {
			switch (getHoleType(hole, $rollMetadata.ROLL_TYPE)) {
				case "pedal":
					hole.color = pedalHoleColor;
					hole.type = "pedal";
					break;
				case "control":
					hole.color = controlHoleColor;
					hole.type = "control";
					break;
				case "note":
					hole.color = getNoteHoleColor(hole);
					hole.type = "note";
					break;
				default:
					hole.color = defaultHoleColor;
			}
		});
	};

	let osdNavDisplayRegion;

	const createMark = hole => {
		const { x: offsetX, y: offsetY, w: width, h: height, m: midiKey, v: velocity, color: holeColor, type: holeType } = hole;
		const mark = document.createElement("mark");
		const holeLabel = getHoleLabel(midiKey, $rollMetadata.ROLL_TYPE);
		mark.dataset.holeLabel = holeLabel;
		if (holeType === "note") mark.dataset.noteVelocity = velocity || 64;
		mark.style.setProperty("--highlight-color", `hsl(${holeColor})`);
		mark.classList.add(holeType);

		mark.addEventListener("mouseout", () => {
			if (!marks.map(([_hole]) => _hole).includes(hole)) viewport.viewer.removeOverlay(hoveredMark);
		});

		const imgBounds = viewport.viewportToImageRectangle(viewport.getBounds());
		const markFractionalPosition = parseFloat(offsetX + width / 2 - imgBounds.x) / parseFloat(imgBounds.width);
		mark.classList.toggle("flag-left", markFractionalPosition > 0.8);

		const viewportRectangle = viewport.imageToViewportRectangle(
			offsetX - 4,
			scrollDownwards
			? offsetY - 4
			: imageLength - offsetY - height - 4,
			width + 11,
			height + 12
		);

		viewport.viewer.addOverlay(mark, viewportRectangle);
		return mark;
	};

	const createHolesOverlaySvg = () => {
		const { holeData } = $rollMetadata;
		if (!holeData) return;
		const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
		const g = document.createElementNS("http://www.w3.org/2000/svg", "g");
		const entireViewportRectangle = viewport.imageToViewportRectangle(0, 0, imageWidth, imageLength);
		svg.setAttribute("width", imageWidth);
		svg.setAttribute("height", imageLength);
		svg.setAttribute("viewBox", `0 0 ${imageWidth} ${imageLength}`);
		svg.appendChild(g);

		holeData.forEach(hole => {
			const rect = document.createElementNS("http://www.w3.org/2000/svg", "rect");
			const { x: offsetX, y: offsetY, w: width, h: height, color: holeColor, type: holeType } = hole;
			const padding = 10;
			rect.setAttribute("x", offsetX - padding);

			rect.setAttribute("y", scrollDownwards
			? offsetY - padding
			: imageLength - offsetY - height - padding);

			rect.setAttribute("width", width + padding * 2);
			rect.setAttribute("height", height + padding * 2);
			rect.setAttribute("rx", 10);
			rect.setAttribute("ry", 10);

			rect.addEventListener("mouseover", () => {
				if (marks.map(([_hole]) => _hole).includes(hole)) return;
				viewport.viewer.removeOverlay(hoveredMark);
				hoveredMark = createMark(hole);
			});

			rect.setAttribute("fill", `hsla(${holeColor}, 0.8)`);
			rect.setAttribute("class", holeType);
			g.appendChild(rect);
		});

		viewport.viewer.addOverlay(svg, entireViewportRectangle);
	};

	const advanceToTick = tick => {
		if (!openSeadragon) return;
		const linePx = firstHolePx + (scrollDownwards ? tick : -tick);
		const lineViewport = viewport.imageToViewportCoordinates(0, linePx);

		if ($animatePan) {
			viewport.centerSpringY.springTo(lineViewport.y);
		} else {
			viewport.centerSpringY.resetTo(lineViewport.y);
		}

		osdNavDisplayRegion.dataset.label = ($playbackProgress * 100).toFixed(1);
		osdNavDisplayRegion.classList.toggle("label-above", $playbackProgress > 0.5);
	};

	const highlightHoles = tick => {
		if (!openSeadragon) return;
		const holes = holesByTickInterval.search(tick, tick);

		marks = marks.filter(([hole, elem]) => {
			if (holes.includes(hole)) return true;
			viewport.viewer.removeOverlay(elem);
			return false;
		});

		holes.forEach(hole => {
			if (marks.map(([_hole]) => _hole).includes(hole)) return;
			const mark = createMark(hole);
			mark.classList.add("active");
			marks.push([hole, mark]);
		});
	};

	onMount(async () => {
		$$invalidate(0, openSeadragon = OpenSeadragon({
			id: "roll-viewer",
			showNavigationControl: false,
			panHorizontal: true,
			visibilityRatio: 1,
			defaultZoomLevel,
			minZoomLevel,
			maxZoomLevel,
			constrainDuringPan: true,
			preserveImageSizeOnResize: true,
			gestureSettingsMouse: { clickToZoom: false, scrollToZoom: false },
			showNavigator: true,
			navigatorAutoFade: false,
			navigatorPosition: "ABSOLUTE",
			navigatorTop: "0px",
			navigatorLeft: "calc(100% - 40px)",
			navigatorHeight: "100%",
			navigatorWidth: "40px",
			navigatorDisplayRegionColor: "transparent"
		}));

		$$invalidate(1, { viewport } = openSeadragon, viewport);
		osdNavDisplayRegion = openSeadragon.navigator.displayRegion;

		// Override some styles that OSD sets directly on the elements
		$$invalidate(0, openSeadragon.navigator.element.style.border = "none", openSeadragon);

		$$invalidate(0, openSeadragon.navigator.element.parentElement.style.backgroundColor = "#666", openSeadragon);
		$$invalidate(0, openSeadragon.navigator.displayRegion.style.display = "block", openSeadragon);
		$$invalidate(0, openSeadragon.navigator.displayRegion.style.border = "none", openSeadragon);
		$$invalidate(0, openSeadragon.navigator.displayRegion.style.overflow = "visible", openSeadragon);
		$$invalidate(0, openSeadragon.navigator.displayRegion.style.left = "0", openSeadragon);
		$$invalidate(0, openSeadragon.navigator.displayRegion.style.width = "100%", openSeadragon);
		$$invalidate(0, openSeadragon.navigator.displayRegion.style.backgroundColor = "rgba(255 255 255 / .6)", openSeadragon);
		$$invalidate(0, openSeadragon.navigator.displayRegion.style.boxShadow = "0 0 4px var(--primary-accent)", openSeadragon);

		$$invalidate(
			0,
			openSeadragon.navigator.update = function navUpdate(mainViewport) {
				// reimplemented based on
				// https://github.com/openseadragon/openseadragon/blob/6cb2c9e7bc4adebe28e386a093890a6c3e353c6b/src/navigator.js#L342-L393
				const { viewport: navViewport, displayRegion: { style }, totalBorderWidths } = this;

				if (mainViewport && navViewport) {
					const bounds = viewport.getBoundsNoRotate(true);
					const topleft = navViewport.pixelFromPointNoRotate(bounds.getTopLeft(), false);
					const bottomright = navViewport.pixelFromPointNoRotate(bounds.getBottomRight(), false).minus(totalBorderWidths);
					style.top = `${Math.round(topleft.y)}px`;
					style.height = `${Math.abs(topleft.y - bottomright.y)}px`;
				}
			},
			openSeadragon
		);

		openSeadragon.addOnceHandler("update-viewport", () => {
			createHolesOverlaySvg();
			advanceToTick(0);
		});

		openSeadragon.addHandler("canvas-drag", () => $$invalidate(2, strafing = true));
		openSeadragon.addHandler("canvas-drag-end", () => $$invalidate(2, strafing = false));

		openSeadragon.addHandler("pan", ({ immediately }) => {
			if (immediately) return;
			const viewportCenter = viewport.getCenter(false);
			const imgCenter = viewport.viewportToImageCoordinates(viewportCenter);

			skipToTick(scrollDownwards
			? imgCenter.y - firstHolePx
			: firstHolePx - imgCenter.y);
		});

		openSeadragon.addHandler("open", () => {
			const tiledImage = viewport.viewer.world.getItemAt(0);
			tiledImage.addOnceHandler("fully-loaded-change", () => $$invalidate(3, rollImageReady = true));
		});

		openSeadragon.addHandler("zoom", ({ zoom }) => {
			const imageZoom = viewport.viewportToImageZoom(zoom);
			$$invalidate(5, trackerbarHeight = Math.max(1, avgHoleWidth * imageZoom));
		});

		openSeadragon.open(imageUrl);
	});

	const panByIncrement = (up = true) => {
		const viewportBounds = viewport.getBounds();
		const imgBounds = viewport.viewportToImageRectangle(viewportBounds);
		const delta = up ? imgBounds.height / 200 : -imgBounds.height / 200;
		const centerY = imgBounds.y + imgBounds.height / 2;

		skipToTick(scrollDownwards
		? clamp(centerY + delta - firstHolePx, -firstHolePx, imageLength - firstHolePx)
		: clamp(firstHolePx - centerY - delta, firstHolePx - imageLength, firstHolePx));
	};

	function rollviewercontrols_strafing_binding(value) {
		strafing = value;
		$$invalidate(2, strafing);
	}

	const mouseenter_handler = () => $$invalidate(4, showControls = true);
	const mouseleave_handler = () => $$invalidate(4, showControls = false);

	const wheel_handler = event => {
		if (event.ctrlKey) {
			panByIncrement(event.deltaY > 0);
			event.stopPropagation();
			return;
		}

		viewport.zoomTo(Math.min(viewport.getZoom() * (event.deltaY > 0 ? 0.9 : 1.1), maxZoomLevel));
	};

	$$self.$$set = $$props => {
		if ('imageUrl' in $$props) $$invalidate(10, imageUrl = $$props.imageUrl);
		if ('holesByTickInterval' in $$props) $$invalidate(11, holesByTickInterval = $$props.holesByTickInterval);
		if ('skipToTick' in $$props) $$invalidate(12, skipToTick = $$props.skipToTick);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty[0] & /*$currentTick*/ 32768) {
			$: advanceToTick($currentTick);
		}

		if ($$self.$$.dirty[0] & /*$currentTick*/ 32768) {
			$: highlightHoles($currentTick);
		}

		if ($$self.$$.dirty[0] & /*$rollMetadata*/ 16384) {
			$: calculateHoleColors($rollMetadata.holeData);
		}

		if ($$self.$$.dirty[0] & /*$rollMetadata*/ 16384) {
			$: $$invalidate(13, scrollDownwards = $rollMetadata.ROLL_TYPE === "welte-red");
		}

		if ($$self.$$.dirty[0] & /*$rollMetadata*/ 16384) {
			$: imageLength = parseInt($rollMetadata.IMAGE_LENGTH, 10);
		}

		if ($$self.$$.dirty[0] & /*$rollMetadata*/ 16384) {
			$: imageWidth = parseInt($rollMetadata.IMAGE_WIDTH, 10);
		}

		if ($$self.$$.dirty[0] & /*$rollMetadata*/ 16384) {
			$: avgHoleWidth = parseInt($rollMetadata.AVG_HOLE_WIDTH, 10);
		}

		if ($$self.$$.dirty[0] & /*scrollDownwards, $rollMetadata*/ 24576) {
			$: firstHolePx = scrollDownwards
			? parseInt($rollMetadata.FIRST_HOLE, 10)
			: parseInt($rollMetadata.IMAGE_LENGTH, 10) - parseInt($rollMetadata.FIRST_HOLE, 10);
		}
	};

	return [
		openSeadragon,
		viewport,
		strafing,
		rollImageReady,
		showControls,
		trackerbarHeight,
		$userSettings,
		$rollPedalingOnOff,
		$playExpressionsOnOff,
		panByIncrement,
		imageUrl,
		holesByTickInterval,
		skipToTick,
		scrollDownwards,
		$rollMetadata,
		$currentTick,
		rollviewercontrols_strafing_binding,
		mouseenter_handler,
		mouseleave_handler,
		wheel_handler
	];
}

class RollViewer extends SvelteComponent {
	constructor(options) {
		super();

		init(
			this,
			options,
			instance,
			create_fragment,
			safe_not_equal,
			{
				imageUrl: 10,
				holesByTickInterval: 11,
				skipToTick: 12
			},
			null,
			[-1, -1]
		);
	}
}

export default RollViewer;