import './RollDetails.svelte.css.proxy.js';
/* src/components/RollDetails.svelte generated by Svelte v3.29.4 */
import {
	SvelteComponent,
	append,
	attr,
	component_subscribe,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	set_data,
	text
} from "../_snowpack/pkg/svelte/internal.js";

import { rollMetadata } from "../stores.js";

function create_fragment(ctx) {
	let dl;
	let dt0;
	let dd0;
	let t1_value = /*$rollMetadata*/ ctx[0].TITLE + "";
	let t1;
	let dt1;
	let dd1;
	let t3_value = /*$rollMetadata*/ ctx[0].PERFORMER + "";
	let t3;
	let dt2;
	let dd2;
	let t5_value = /*$rollMetadata*/ ctx[0].COMPOSER + "";
	let t5;
	let dt3;
	let dd3;
	let t7_value = /*$rollMetadata*/ ctx[0].LABEL + "";
	let t7;
	let dt4;
	let dd4;
	let a;
	let t9_value = /*$rollMetadata*/ ctx[0].PURL + "";
	let t9;
	let a_href_value;
	let dt5;
	let dd5;
	let t11_value = /*$rollMetadata*/ ctx[0].CALLNUM + "";
	let t11;

	return {
		c() {
			dl = element("dl");
			dt0 = element("dt");
			dt0.textContent = "Title";
			dd0 = element("dd");
			t1 = text(t1_value);
			dt1 = element("dt");
			dt1.textContent = "Performer";
			dd1 = element("dd");
			t3 = text(t3_value);
			dt2 = element("dt");
			dt2.textContent = "Composer";
			dd2 = element("dd");
			t5 = text(t5_value);
			dt3 = element("dt");
			dt3.textContent = "Label";
			dd3 = element("dd");
			t7 = text(t7_value);
			dt4 = element("dt");
			dt4.textContent = "PURL";
			dd4 = element("dd");
			a = element("a");
			t9 = text(t9_value);
			dt5 = element("dt");
			dt5.textContent = "Call No";
			dd5 = element("dd");
			t11 = text(t11_value);
			attr(dt0, "class", "svelte-191eahf");
			attr(dt1, "class", "svelte-191eahf");
			attr(dt2, "class", "svelte-191eahf");
			attr(dt3, "class", "svelte-191eahf");
			attr(dt4, "class", "svelte-191eahf");
			attr(a, "href", a_href_value = /*$rollMetadata*/ ctx[0].PURL);
			attr(dt5, "class", "svelte-191eahf");
			attr(dl, "class", "svelte-191eahf");
		},
		m(target, anchor) {
			insert(target, dl, anchor);
			append(dl, dt0);
			append(dl, dd0);
			append(dd0, t1);
			append(dl, dt1);
			append(dl, dd1);
			append(dd1, t3);
			append(dl, dt2);
			append(dl, dd2);
			append(dd2, t5);
			append(dl, dt3);
			append(dl, dd3);
			append(dd3, t7);
			append(dl, dt4);
			append(dl, dd4);
			append(dd4, a);
			append(a, t9);
			append(dl, dt5);
			append(dl, dd5);
			append(dd5, t11);
		},
		p(ctx, [dirty]) {
			if (dirty & /*$rollMetadata*/ 1 && t1_value !== (t1_value = /*$rollMetadata*/ ctx[0].TITLE + "")) set_data(t1, t1_value);
			if (dirty & /*$rollMetadata*/ 1 && t3_value !== (t3_value = /*$rollMetadata*/ ctx[0].PERFORMER + "")) set_data(t3, t3_value);
			if (dirty & /*$rollMetadata*/ 1 && t5_value !== (t5_value = /*$rollMetadata*/ ctx[0].COMPOSER + "")) set_data(t5, t5_value);
			if (dirty & /*$rollMetadata*/ 1 && t7_value !== (t7_value = /*$rollMetadata*/ ctx[0].LABEL + "")) set_data(t7, t7_value);
			if (dirty & /*$rollMetadata*/ 1 && t9_value !== (t9_value = /*$rollMetadata*/ ctx[0].PURL + "")) set_data(t9, t9_value);

			if (dirty & /*$rollMetadata*/ 1 && a_href_value !== (a_href_value = /*$rollMetadata*/ ctx[0].PURL)) {
				attr(a, "href", a_href_value);
			}

			if (dirty & /*$rollMetadata*/ 1 && t11_value !== (t11_value = /*$rollMetadata*/ ctx[0].CALLNUM + "")) set_data(t11, t11_value);
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(dl);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let $rollMetadata;
	component_subscribe($$self, rollMetadata, $$value => $$invalidate(0, $rollMetadata = $$value));
	return [$rollMetadata];
}

class RollDetails extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default RollDetails;