// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = "#roll-viewer.svelte-zzqd0t.svelte-zzqd0t{position:relative;height:100%;width:100%}#roll-viewer.svelte-zzqd0t p.svelte-zzqd0t{background:rgba(0, 0, 0, 0.4);border-radius:4px;color:white;left:1em;padding:4px 8px;position:absolute;top:1em;z-index:1}#roll-viewer.svelte-zzqd0t.svelte-zzqd0t::before{background-color:var(--primary-accent-semiopaque);border:1px solid var(--primary-accent);content:\"\";display:block;height:var(--trackerbar-height);pointer-events:none;position:absolute;top:50%;width:100%;z-index:1}#roll-viewer.svelte-zzqd0t.svelte-zzqd0t::after{background:linear-gradient(var(--background-angle), var(--background-darker) 0%, var(--background-color) 25%, var(--background-color) 75%, var(--background-darker) 100%);background-attachment:fixed;background-position:center;bottom:0;content:\" \";left:0;mix-blend-mode:multiply;pointer-events:none;position:absolute;right:0;top:0}#roll-viewer.svelte-zzqd0t mark{background-color:transparent}#roll-viewer.svelte-zzqd0t mark:hover{background-color:transparent;box-shadow:none;outline:6px solid darkturquoise;outline-offset:8px;z-index:1}#roll-viewer.svelte-zzqd0t mark:hover::before{height:0;position:relative}#roll-viewer.svelte-zzqd0t mark.active::before{position:absolute;content:\"\";top:0;left:0;bottom:0;right:0;mix-blend-mode:multiply;animation:svelte-zzqd0t-mark-recede 0.5s ease-in-out;background-color:yellow;box-shadow:0 0 5px yellow;display:inline-block}#roll-viewer.svelte-zzqd0t mark:hover[data-info]::after{background-color:darkturquoise;color:white;content:attr(data-info);display:block;font-weight:bold;left:calc( 100% + 8px + 6px );padding:8px 10px 8px 4px;position:absolute;text-shadow:0px 0px 8px black;top:-14px;transform:none}#roll-viewer.svelte-zzqd0t mark.flag-left:hover[data-info]::after{left:auto;right:calc( 100% + 8px + 6px );padding:8px 4px 8px 10px}#roll-viewer.svelte-zzqd0t canvas{background:white !important}#roll-viewer.svelte-zzqd0t .openseadragon-canvas:focus{outline:none}#roll-viewer.svelte-zzqd0t svg rect{fill:none;pointer-events:all}#roll-viewer.active-note-details.svelte-zzqd0t mark.active[data-info]::after{background-color:none;color:white;content:attr(data-info);display:block;font-weight:bold;left:50%;padding:8px 4px;position:absolute;text-shadow:0px 0px 8px black;top:0;mix-blend-mode:normal;transform:translate(-50%, -100%)}#roll-viewer.active-note-details.svelte-zzqd0t mark.active[data-info]:hover::after{left:calc( 100% + 8px + 6px );top:-14px;transform:none}@keyframes svelte-zzqd0t-mark-recede{from{border-radius:30%;mix-blend-mode:normal}}";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}