import './Notification.svelte.css.proxy.js';
/* src/ui-components/Notification.svelte generated by Svelte v3.41.0 */
import {
	SvelteComponent,
	append,
	attr,
	component_subscribe,
	detach,
	element,
	empty,
	init,
	insert,
	listen,
	noop,
	safe_not_equal,
	set_data,
	space,
	text
} from "../_snowpack/pkg/svelte/internal.js";

import { writable } from "../_snowpack/pkg/svelte/store.js";

function create_if_block(ctx) {
	let div;
	let section;
	let t0;
	let p;
	let raw_value = /*$NotificationStore*/ ctx[0].message + "";
	let t1;
	let div_class_value;
	let if_block0 = /*$NotificationStore*/ ctx[0].title && create_if_block_2(ctx);
	let if_block1 = /*$NotificationStore*/ ctx[0].closable !== false && create_if_block_1(ctx);

	return {
		c() {
			div = element("div");
			section = element("section");
			if (if_block0) if_block0.c();
			t0 = space();
			p = element("p");
			t1 = space();
			if (if_block1) if_block1.c();
			attr(p, "class", "svelte-1j2pchn");
			attr(section, "class", "svelte-1j2pchn");
			attr(div, "class", div_class_value = "notification " + (/*$NotificationStore*/ ctx[0].type || 'default') + " svelte-1j2pchn");
		},
		m(target, anchor) {
			insert(target, div, anchor);
			append(div, section);
			if (if_block0) if_block0.m(section, null);
			append(section, t0);
			append(section, p);
			p.innerHTML = raw_value;
			append(div, t1);
			if (if_block1) if_block1.m(div, null);
		},
		p(ctx, dirty) {
			if (/*$NotificationStore*/ ctx[0].title) {
				if (if_block0) {
					if_block0.p(ctx, dirty);
				} else {
					if_block0 = create_if_block_2(ctx);
					if_block0.c();
					if_block0.m(section, t0);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (dirty & /*$NotificationStore*/ 1 && raw_value !== (raw_value = /*$NotificationStore*/ ctx[0].message + "")) p.innerHTML = raw_value;;

			if (/*$NotificationStore*/ ctx[0].closable !== false) {
				if (if_block1) {
					if_block1.p(ctx, dirty);
				} else {
					if_block1 = create_if_block_1(ctx);
					if_block1.c();
					if_block1.m(div, null);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (dirty & /*$NotificationStore*/ 1 && div_class_value !== (div_class_value = "notification " + (/*$NotificationStore*/ ctx[0].type || 'default') + " svelte-1j2pchn")) {
				attr(div, "class", div_class_value);
			}
		},
		d(detaching) {
			if (detaching) detach(div);
			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
		}
	};
}

// (66:6) {#if $NotificationStore.title}
function create_if_block_2(ctx) {
	let header;
	let t_value = /*$NotificationStore*/ ctx[0].title + "";
	let t;

	return {
		c() {
			header = element("header");
			t = text(t_value);
			attr(header, "class", "svelte-1j2pchn");
		},
		m(target, anchor) {
			insert(target, header, anchor);
			append(header, t);
		},
		p(ctx, dirty) {
			if (dirty & /*$NotificationStore*/ 1 && t_value !== (t_value = /*$NotificationStore*/ ctx[0].title + "")) set_data(t, t_value);
		},
		d(detaching) {
			if (detaching) detach(header);
		}
	};
}

// (71:4) {#if $NotificationStore.closable !== false}
function create_if_block_1(ctx) {
	let div;
	let mounted;
	let dispose;

	return {
		c() {
			div = element("div");
			div.textContent = "×";
			attr(div, "class", "close svelte-1j2pchn");
		},
		m(target, anchor) {
			insert(target, div, anchor);

			if (!mounted) {
				dispose = listen(div, "click", /*click_handler*/ ctx[1]);
				mounted = true;
			}
		},
		p: noop,
		d(detaching) {
			if (detaching) detach(div);
			mounted = false;
			dispose();
		}
	};
}

function create_fragment(ctx) {
	let if_block_anchor;
	let if_block = /*$NotificationStore*/ ctx[0] && create_if_block(ctx);

	return {
		c() {
			if (if_block) if_block.c();
			if_block_anchor = empty();
		},
		m(target, anchor) {
			if (if_block) if_block.m(target, anchor);
			insert(target, if_block_anchor, anchor);
		},
		p(ctx, [dirty]) {
			if (/*$NotificationStore*/ ctx[0]) {
				if (if_block) {
					if_block.p(ctx, dirty);
				} else {
					if_block = create_if_block(ctx);
					if_block.c();
					if_block.m(if_block_anchor.parentNode, if_block_anchor);
				}
			} else if (if_block) {
				if_block.d(1);
				if_block = null;
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (if_block) if_block.d(detaching);
			if (detaching) detach(if_block_anchor);
		}
	};
}

const NotificationStore = writable();
const notify = detail => NotificationStore.set(detail);

function instance($$self, $$props, $$invalidate) {
	let $NotificationStore;
	component_subscribe($$self, NotificationStore, $$value => $$invalidate(0, $NotificationStore = $$value));
	const click_handler = () => NotificationStore.set();
	return [$NotificationStore, click_handler];
}

class Notification extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Notification;
export { notify };