// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = "[type=range].svelte-1e6cgmk{-webkit-appearance:none;background:transparent;margin:9px 0;width:18em}[type=range].svelte-1e6cgmk::-moz-focus-outer{border:0}[type=range].svelte-1e6cgmk:focus{outline:0}[type=range].svelte-1e6cgmk:focus::-webkit-slider-runnable-track{background:#f7f7f7}[type=range].svelte-1e6cgmk:focus::-ms-fill-lower{background:#eaeaea}[type=range].svelte-1e6cgmk:focus::-ms-fill-upper{background:#f7f7f7}[type=range].svelte-1e6cgmk::-webkit-slider-runnable-track{cursor:default;height:8px;transition:all 0.2s ease;width:100%;box-shadow:1px 1px 1px rgba(0, 0, 0, 0.2), 0 0 1px rgba(13, 13, 13, 0.2);background:#eaeaea;border:0px solid #cfd8dc;border-radius:5px}[type=range].svelte-1e6cgmk::-webkit-slider-thumb{box-shadow:2px 2px 4px rgba(0, 0, 0, 0.2), 0 0 2px rgba(13, 13, 13, 0.2);background:#8c1515;border:2px solid #eaeaea;border-radius:12px;box-sizing:border-box;cursor:default;height:18px;width:24px;-webkit-appearance:none;margin-top:-5px}[type=range].svelte-1e6cgmk::-moz-range-track{box-shadow:1px 1px 1px rgba(0, 0, 0, 0.2), 0 0 1px rgba(13, 13, 13, 0.2);cursor:default;height:8px;transition:all 0.2s ease;width:100%;background:#eaeaea;border:0px solid #cfd8dc;border-radius:5px;height:4px}[type=range].svelte-1e6cgmk::-moz-range-thumb{box-shadow:2px 2px 4px rgba(0, 0, 0, 0.2), 0 0 2px rgba(13, 13, 13, 0.2);background:#8c1515;border:2px solid #eaeaea;border-radius:12px;box-sizing:border-box;cursor:default;height:18px;width:24px}[type=range].svelte-1e6cgmk::-ms-track{cursor:default;height:8px;transition:all 0.2s ease;width:100%;background:transparent;border-color:transparent;border-width:9px 0;color:transparent}[type=range].svelte-1e6cgmk::-ms-fill-lower{box-shadow:1px 1px 1px rgba(0, 0, 0, 0.2), 0 0 1px rgba(13, 13, 13, 0.2);background:#dddddd;border:0px solid #cfd8dc;border-radius:10px}[type=range].svelte-1e6cgmk::-ms-fill-upper{box-shadow:1px 1px 1px rgba(0, 0, 0, 0.2), 0 0 1px rgba(13, 13, 13, 0.2);background:#eaeaea;border:0px solid #cfd8dc;border-radius:10px}[type=range].svelte-1e6cgmk::-ms-thumb{box-shadow:2px 2px 4px rgba(0, 0, 0, 0.2), 0 0 2px rgba(13, 13, 13, 0.2);background:#8c1515;border:2px solid #eaeaea;border-radius:12px;box-sizing:border-box;cursor:default;height:18px;width:24px;margin-top:2px}[type=range].svelte-1e6cgmk:disabled::-webkit-slider-thumb,[type=range].svelte-1e6cgmk:disabled::-moz-range-thumb,[type=range].svelte-1e6cgmk:disabled::-ms-thumb,[type=range].svelte-1e6cgmk:disabled::-webkit-slider-runnable-track,[type=range].svelte-1e6cgmk:disabled::-ms-fill-lower,[type=range].svelte-1e6cgmk:disabled::-ms-fill-upper{cursor:not-allowed}";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}